# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "davidnilo.com"
email: davidnilo94@gmail.com
description: "Blog de David Nilo"
url: http://davidnilo.com # the base hostname & protocol for your site, e.g. http://example.com
baseurl:
lang: es_ES
logo: /assets/logos/logo.png
twitter:
  username:
facebook:
  publisher:
  app_id:

social:
  type: Person # Person or Organization (defaults to Person)
  links: # An array of links to social media profiles
    - https://www.linkedin.com/in/david-nilo-muñoz-bastardo-b14428b7/
    - https://www.facebook.com/david.nilo.3?ref=bookmarks
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
google_analytics: UA-116304412-1

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true
sass:
    style: compressed

# Plugins (previously gems:)
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Outputting
permalink: pretty
paginate: 9 # amount of posts to show
paginate_path: /noticias/:num/
timezone: Europe/Madrid # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: posts
  - scope:
      path: ""
      type: pages
    values:
      image: /assets/logos/logo.png
include:
  - _pages
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

keep_files: [media, assets/logos, assets/imagenes]

prose:
  rooturl: '_posts'
  siteurl: 'http://davidnilo.com/'
  relativeLinks: 'http://davidnilo.com/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "posts"
      - name: "title"
        field:
          element: "text"
          label: "Titulo"
          value:
      - name: "description"
        field:
          element: "text"
          label: "Descripcion"
          value:
      - name: "image"
        field:
          element: "text"
          label: "imagen"
          value: "/media/"
      - name: "disqus"
        field:
          element: "checkbox"
          label: "Comentarios"
          value: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publicar"
          value: false
